{{- if not .Values.global.limitedScope }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.0
  name: federation-role
rules:
- apiGroups:
  - scheduling.federation.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
  - update
- apiGroups:
  - multiclusterdns.federation.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - delete
- apiGroups:
  - core.federation.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
  - create
  - update
- apiGroups:
  - types.federation.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
  - update
- apiGroups:
  - clusterregistry.k8s.io
  resources:
  - clusters
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - events
  - namespaces
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
{{- end }}
